# Generated by Django 2.2.4 on 2020-04-29 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OnlineHobbies', '0002_auto_20200428_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclassenroll',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
