# Generated by Django 2.2.4 on 2020-04-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hobbies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='image',
            field=models.ImageField(null=True, upload_to='User/images'),
        ),
    ]
