# Generated by Django 2.2.6 on 2020-04-29 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_remove_cartitem_hobbies'),
        ('Hobbies', '0002_hobbies_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='User/images')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hobbies',
        ),
    ]
