# Generated by Django 2.2.4 on 2020-04-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(null=True, to='Cart.CartItem'),
        ),
    ]
