# Generated by Django 2.2.6 on 2020-04-29 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_auto_20200404_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='hobbies',
        ),
    ]
