# Generated by Django 2.2.6 on 2020-04-29 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hobbies', '0003_auto_20200428_2253'),
        ('Cart', '0003_remove_cartitem_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hobbies.Inclass'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='Cart.CartItem'),
        ),
    ]
